spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://14.225.210.86:3306/electronic_db?autoReconnect=true&useSSL=false
    username: root
    password: rootpw12345
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    hibernate:
      ddl-auto: none
  messages:
    basename: messageErrors
    fallback-to-system-locale: false
  web:
    locale: vi_VN
    locale-resolver: fixed
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: phusnps19247@fpt.edu.vn
    password: dpwznhbmjocstyxm
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: false #false is not use liquibase when no have new design
  logging:
    level:
      org:
        hibernate: ERROR
  app:
    jwtRefreshExpirationMs: 6000
    jwtExpirationMs: 60000
    jwtSecret: BonikSecret13296725921461123321123BonikSecret
    jwtCookieName: bonik
    jwtRefreshCookieName: bonikRF
    cors:
      allowedOrigins: http://localhost:3000,http://localhost:3001,http://localhost:8080,https://bonikphone.shop/swagger-ui/index.html,https://bonikphone.shop/,https://admin.bonikphone.shop/,https://api.bonikphone.shop/,https://user.longproxy.com,https://admin.longproxy.com
    oauth2:
      # After successfully authenticating with the OAuth2 Provider,
      # we'll be generating an auth token for the user and sending the token to the
      # redirectUri mentioned by the client in the /oauth2/authorize request.
      authorizedRedirectUris:
        - http://localhost:3000/
        - https://bonikphone.shop/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 496256023815-gfnv445ste0ep1o56qqr2j7ffggbd17s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://api.bonikphone.shop/oauth2/callback
            scope:
              - email
              - profile
